services:
  db:
    image: pgvector/pgvector:pg16
    container_name: api-tasks-db
    environment:
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: tasks_pass
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
