"""create task_embeddings table

Revision ID: 731d879d91b9
Revises: ec6ffc0dd32a
Create Date: 2026-07-04 12:39:52.591908

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "731d879d91b9"
down_revision: Union[str, Sequence[str], None] = "ec6ffc0dd32a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(dim=1536), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_embeddings_task_id"), "task_embeddings", ["task_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_embeddings_task_id"), table_name="task_embeddings")
    op.drop_table("task_embeddings")
    # ### end Alembic commands ###
